version: "3"
services:

#######
# 172.17.1.127 = SERVER IP
#######

  # gc
  gc:
    image: spotify/docker-gc
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc:/etc:ro
    privileged: true
    environment:
      - GRACE_PERIOD_SECONDS=18000
    networks:
      - storagenet

###################################################################

  mongo27017:
    image: mongo:4.2-bionic
    volumes:
      - ./volumes/mongo/27017:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - "27017:27017"
    networks:
      storagenet:
        ipv4_address: 172.200.0.151

###################################################################

  kafka-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      storagenet:
        ipv4_address: 172.200.0.191

  kafka-broker:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    networks:
      storagenet:
        ipv4_address: 172.200.0.192
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.1.127
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181

  kafka-connect:
    image: confluentinc/cp-kafka-connect:5.3.1
    ports:
      - "8083:8083"
    networks:
      storagenet:
        ipv4_address: 172.200.0.193
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka-broker:9092"
      CONNECT_REST_ADVERTISED_HOST_NAME: "172.17.1.127"
      CONNECT_REST_PORT: "8083"
      CONNECT_GROUP_ID: test-dev-connect
      CONNECT_CONFIG_STORAGE_TOPIC: connect-storage-config
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: connect-storage-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: connect-storage-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR,com.mongodb.kafka=DEBUG"
      CONNECT_PLUGIN_PATH: "/usr/share/confluent-hub-components"
      CONNECT_ZOOKEEPER_CONNECT: "kafka-zookeeper:2181"
    # volumes / plugins
    volumes:
      - ./kafka-connect-mongodb:/usr/share/confluent-hub-components/kafka-connect-mongodb

###################################################################

networks:
  storagenet:
    ipam:
      driver: default
      config:
      - subnet: "172.200.0.0/24"
